#!/usr/bin/env python3
"""The sealing seam: the amiitool port, the identity coordinates and the cache.

The oracle is amiitool's own output (`fixtures/sealing`, regenerated by
`scripts/build_sealing_fixture.py`) and, when the clone is mounted, the real
library's own tags. What is pinned: the intake slice, the two coordinate
systems, both HMACs, per-placement re-sealing, and the fact that a placement
cannot silently replay a stored dump — the one failure mode that looks like
success (§6.7).

Run:  python3 -m unittest discover -s container/tests -p 'test_ns2sealing*.py'
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import support  # noqa: E402

from container.ns2sealing import (  # noqa: E402
    INTERNAL_DATA_HMAC_OFFSET,
    INTERNAL_IDENTITY_OFFSET,
    INTERNAL_LENGTH,
    INTERNAL_TAG_HMAC_OFFSET,
    TAG_DATA_HMAC_OFFSET,
    TAG_IDENTITY_OFFSET,
    TAG_IMAGE_LENGTH,
    TAG_TAG_HMAC_OFFSET,
    TRAILER_LENGTH,
    KeyInvalid,
    KeyMaterial,
    Plaintext,
    SealedTag,
    Sealer,
    TagInvalid,
    bcc0_for,
    bcc1_for,
    identity_block_for,
    identity_of,
    mint_identity,
    pack,
    seal,
    slice_tag_image,
    unpack,
)

SAMUS_IMAGE = bytes.fromhex("0411fe63ca526c81") + bytes(TAG_IMAGE_LENGTH - 8)


class FixtureKey:
    """The synthetic key, the tag amiitool sealed, and amiitool's own outputs."""

    key_bytes = support.sealing_fixture("key")
    tag = support.sealing_fixture("tag")
    plain = support.sealing_fixture("plain")
    trailer = support.sealing_fixture("trailer")
    identity = support.sealing_fixture("identity")
    sealed = support.sealing_fixture("sealed")

    @classmethod
    def key(cls) -> KeyMaterial:
        return KeyMaterial(cls.key_bytes)

    @classmethod
    def rewritten_plain(cls) -> Plaintext:
        """`plain` with the fresh identity written in, **as the generator did**.

        The byte surgery is repeated here on purpose rather than calling
        `Plaintext.with_identity`: this is the oracle's input, and building it
        with the code under test would make the test agree with the code by
        construction.
        """
        internal = bytearray(cls.plain)
        internal[INTERNAL_IDENTITY_OFFSET : INTERNAL_IDENTITY_OFFSET + 8] = identity_block_for(cls.identity)
        internal[0] = bcc1_for(cls.identity)
        return Plaintext(internal=bytes(internal), trailer=cls.trailer)


class AmiitoolOracleTest(unittest.TestCase):
    """The fixture is amiitool's output; the port must reproduce it byte for byte."""

    def test_the_fixture_has_the_shape_the_format_fixes(self):
        self.assertEqual(len(FixtureKey.key_bytes), 160)
        self.assertEqual(len(FixtureKey.tag), TAG_IMAGE_LENGTH)
        self.assertEqual(len(FixtureKey.plain), INTERNAL_LENGTH)
        self.assertEqual(len(FixtureKey.trailer), TRAILER_LENGTH)
        self.assertEqual(len(FixtureKey.identity), 7)
        self.assertEqual(len(FixtureKey.sealed), TAG_IMAGE_LENGTH)

    def test_unpack_reproduces_amiitools_own_plaintext(self):
        plain = unpack(FixtureKey.tag, FixtureKey.key())
        self.assertEqual(plain.internal, FixtureKey.plain)
        self.assertEqual(plain.trailer, FixtureKey.trailer)

    def test_pack_reproduces_amiitools_own_sealed_tag(self):
        sealed = pack(FixtureKey.rewritten_plain(), FixtureKey.key())
        self.assertEqual(sealed.image, FixtureKey.sealed)
        self.assertEqual(sealed.identity, FixtureKey.identity)

    def test_seal_matches_amiitool_when_the_identity_is_given(self):
        sealed = seal(FixtureKey.tag, FixtureKey.key(), identity=FixtureKey.identity)
        self.assertEqual(sealed.image, FixtureKey.sealed)
        self.assertEqual(sealed.identity, FixtureKey.identity)

    def test_unpack_requires_both_hmacs(self):
        # The data HMAC at tag 0x080 and the tag HMAC at tag 0x034: each alone
        # is enough to refuse the tag (§6.7's rung 3 is both, not either).
        for offset in (TAG_DATA_HMAC_OFFSET, TAG_TAG_HMAC_OFFSET):
            corrupted = bytearray(FixtureKey.tag)
            corrupted[offset] ^= 0x01
            with self.assertRaises(TagInvalid, msg=f"offset 0x{offset:03x}"):
                unpack(bytes(corrupted), FixtureKey.key())

    def test_unpack_refuses_a_corrupted_ciphertext(self):
        corrupted = bytearray(FixtureKey.tag)
        corrupted[0x100] ^= 0x01
        with self.assertRaises(TagInvalid):
            unpack(bytes(corrupted), FixtureKey.key())

    def test_a_wrong_key_fails_the_round_trip(self):
        wrong = bytearray(FixtureKey.key_bytes)
        wrong[0] ^= 0x01  # a masterkey hmacKey byte; the structure still parses
        with self.assertRaises(TagInvalid):
            unpack(FixtureKey.tag, KeyMaterial(bytes(wrong)))

    def test_the_two_coordinate_systems_are_the_ones_the_spec_fixes(self):
        plain = unpack(FixtureKey.tag, FixtureKey.key())
        self.assertEqual(
            plain.internal[INTERNAL_DATA_HMAC_OFFSET : INTERNAL_DATA_HMAC_OFFSET + 32],
            FixtureKey.tag[TAG_DATA_HMAC_OFFSET : TAG_DATA_HMAC_OFFSET + 32],
        )
        self.assertEqual(
            plain.internal[INTERNAL_TAG_HMAC_OFFSET : INTERNAL_TAG_HMAC_OFFSET + 32],
            FixtureKey.tag[TAG_TAG_HMAC_OFFSET : TAG_TAG_HMAC_OFFSET + 32],
        )
        self.assertEqual(
            plain.internal[INTERNAL_IDENTITY_OFFSET : INTERNAL_IDENTITY_OFFSET + 8],
            FixtureKey.tag[TAG_IDENTITY_OFFSET : TAG_IDENTITY_OFFSET + 8],
        )

    def test_a_sealed_tag_verifies_under_its_own_key(self):
        sealed = seal(FixtureKey.tag, FixtureKey.key())
        plain = unpack(sealed.image, FixtureKey.key())
        self.assertEqual(plain.internal[INTERNAL_IDENTITY_OFFSET : INTERNAL_IDENTITY_OFFSET + 8], identity_block_for(sealed.identity))
        self.assertEqual(len(plain.internal), INTERNAL_LENGTH)

    def test_sealing_is_per_placement_and_never_replays_the_stored_dump(self):
        first = seal(FixtureKey.tag, FixtureKey.key())
        second = seal(FixtureKey.tag, FixtureKey.key())
        self.assertNotEqual(first.identity, second.identity)
        self.assertNotEqual(first.image, second.image)
        for sealed in (first, second):
            self.assertNotEqual(sealed.image, FixtureKey.tag)
            self.assertNotEqual(identity_of(sealed.image), identity_of(FixtureKey.tag))
            unpack(sealed.image, FixtureKey.key())  # both HMACs, under the fresh identity

    def test_the_identity_is_the_kdf_seed_so_a_uid_swap_re_signs(self):
        sealed = seal(FixtureKey.tag, FixtureKey.key(), identity=FixtureKey.identity)
        source = unpack(FixtureKey.tag, FixtureKey.key())
        fresh = unpack(sealed.image, FixtureKey.key())
        self.assertNotEqual(
            source.internal[INTERNAL_TAG_HMAC_OFFSET : INTERNAL_TAG_HMAC_OFFSET + 32],
            fresh.internal[INTERNAL_TAG_HMAC_OFFSET : INTERNAL_TAG_HMAC_OFFSET + 32],
        )
        self.assertNotEqual(
            source.internal[INTERNAL_DATA_HMAC_OFFSET : INTERNAL_DATA_HMAC_OFFSET + 32],
            fresh.internal[INTERNAL_DATA_HMAC_OFFSET : INTERNAL_DATA_HMAC_OFFSET + 32],
        )

    def test_the_configuration_trailer_is_copied_verbatim(self):
        sealed = seal(FixtureKey.tag, FixtureKey.key())
        self.assertEqual(sealed.image[0x208:], FixtureKey.tag[0x208:])

    def test_the_plaintext_left_alone_packs_back_to_amiitools_own_bytes(self):
        # `pack` with no identity keeps the cache's own identity: the pure
        # round trip `pack(unpack(tag)) == tag`, which is what proves the port
        # did not lose the source tag's UID.
        plain = unpack(FixtureKey.tag, FixtureKey.key())
        self.assertEqual(pack(plain, FixtureKey.key()).image, FixtureKey.tag)


class IntakeTest(unittest.TestCase):
    def test_slice_never_trusts_the_file_size(self):
        self.assertEqual(len(slice_tag_image(bytes(572))), TAG_IMAGE_LENGTH)
        self.assertEqual(len(slice_tag_image(bytes(541))), TAG_IMAGE_LENGTH)

    def test_a_short_file_is_refused(self):
        with self.assertRaises(ValueError):
            slice_tag_image(bytes(539))


class IdentityTest(unittest.TestCase):
    def test_the_seven_byte_uid_skips_bcc0(self):
        # §6.3's worked example: 04 11 fe 63 ca 52 6c 81 -> UID 04 11 fe ca 52 6c 81.
        self.assertEqual(identity_of(SAMUS_IMAGE).hex(), "0411feca526c81")

    def test_the_check_bytes_are_recomputed(self):
        identity = identity_of(SAMUS_IMAGE)
        self.assertEqual(bcc0_for(identity), 0x63)
        self.assertEqual(bcc1_for(identity), 0x75)
        self.assertEqual(identity_block_for(identity), SAMUS_IMAGE[0:8])

    def test_a_minted_identity_is_nxp_and_seven_bytes(self):
        identity = mint_identity()
        self.assertEqual(len(identity), 7)
        self.assertEqual(identity[0], 0x04)
        self.assertNotEqual(mint_identity(), mint_identity())


class KeyMaterialTest(unittest.TestCase):
    def test_key_material_is_exactly_160_bytes(self):
        self.assertEqual(len(KeyMaterial(FixtureKey.key_bytes).data), 160)
        with self.assertRaises(KeyInvalid):
            KeyMaterial(FixtureKey.key_bytes[:159])

    def test_a_random_160_byte_file_is_not_a_masterkey_structure(self):
        # §6.7's rung 2: all-zero (and so a random file) fails on the typeStrings.
        with self.assertRaises(KeyInvalid):
            KeyMaterial(bytes(160))

    def test_a_broken_magic_bytes_size_is_refused(self):
        broken = bytearray(FixtureKey.key_bytes)
        broken[31] = 17  # the unfixed-infos masterkey's magicBytesSize
        with self.assertRaises(KeyInvalid):
            KeyMaterial(bytes(broken))


class PlaintextCacheTest(unittest.TestCase):
    """§6.4: unpack lazily, hold in process memory only, copy before rotation."""

    def setUp(self):
        self.sealer = Sealer()
        self.key = FixtureKey.key()

    def test_repeated_placements_unpack_once(self):
        first = self.sealer(FixtureKey.tag, self.key)
        second = self.sealer(FixtureKey.tag, self.key)
        self.assertEqual(self.sealer.cached, 1)
        self.assertEqual(self.sealer.unpacks, 1)
        self.assertNotEqual(first.identity, second.identity)  # still re-sealed

    def test_a_given_identity_is_honoured_and_not_minted(self):
        # The bench's re-presentation step (§6.6, the reference's continue-for-write)
        # seeds `identity`; the sealer must seal that UID, not a fresh one.
        identity = bytes.fromhex("04112233445566")
        sealed = self.sealer(FixtureKey.tag, self.key, identity=identity)
        self.assertEqual(sealed.identity, identity)
        self.assertEqual(identity_of(sealed.image), identity)
        unpack(sealed.image, self.key)

    def test_rotation_copies_the_cache_instead_of_sealing_it_in_place(self):
        first = self.sealer(FixtureKey.tag, self.key)
        cached_after_first = self.sealer.plaintext(FixtureKey.tag, self.key)
        second = self.sealer(FixtureKey.tag, self.key)
        self.assertEqual(self.sealer.plaintext(FixtureKey.tag, self.key).internal, cached_after_first.internal)
        # Both placements carry their own identity; neither corrupted the cache.
        self.assertEqual(identity_of(first.image), first.identity)
        self.assertEqual(identity_of(second.image), second.identity)
        self.assertEqual(
            cached_after_first.internal[INTERNAL_IDENTITY_OFFSET : INTERNAL_IDENTITY_OFFSET + 8],
            identity_block_for(identity_of(FixtureKey.tag)),
        )
        unpack(first.image, self.key)
        unpack(second.image, self.key)

    def test_a_failed_unpack_is_not_cached(self):
        corrupted = bytearray(FixtureKey.tag)
        corrupted[TAG_DATA_HMAC_OFFSET] ^= 0x01
        with self.assertRaises(TagInvalid):
            self.sealer(bytes(corrupted), self.key)
        self.assertEqual(self.sealer.cached, 0)

    def test_the_cache_is_dropped_when_the_key_changes(self):
        self.sealer(FixtureKey.tag, self.key)
        other = bytearray(FixtureKey.key_bytes)
        other[0] ^= 0x01
        with self.assertRaises(TagInvalid):
            self.sealer(FixtureKey.tag, KeyMaterial(bytes(other)))
        self.assertEqual(self.sealer.cached, 0)

    def test_the_sealer_is_a_sealing_seam_like_seal(self):
        sealed = self.sealer(FixtureKey.tag, self.key)
        self.assertIsInstance(sealed, SealedTag)
        self.assertNotEqual(sealed.image, FixtureKey.tag)


@unittest.skipIf(
    support.reference_key_file() is None or support.reference_tag_file() is None,
    "reference Amiibo clone or retail key not present ($REFERENCE_ROOT/Amiibo)",
)
class ReferenceLibraryTest(unittest.TestCase):
    """The acceptance: a library figure seals and verifies against its own tag."""

    @classmethod
    def setUpClass(cls):
        key_file = support.reference_key_file()
        tag_file = support.reference_tag_file()
        assert key_file is not None and tag_file is not None
        cls.key = KeyMaterial(key_file.read_bytes())
        cls.tag_file = tag_file
        cls.tag = slice_tag_image(tag_file.read_bytes())

    def test_a_library_figure_round_trips_against_its_own_tag(self):
        plain = unpack(self.tag, self.key)
        self.assertEqual(pack(plain, self.key).image, self.tag)

    def test_a_library_tag_sealed_under_a_fresh_identity_verifies(self):
        sealed = seal(self.tag, self.key)
        self.assertNotEqual(identity_of(sealed.image), identity_of(self.tag))
        self.assertEqual(sealed.image[0x208:], self.tag[0x208:])
        unpack(sealed.image, self.key)

    def test_the_eleven_572_byte_files_are_sliced_not_mis_read(self):
        directory = support.reference_amiibo_dir()
        assert directory is not None
        oversize = [
            path
            for path in sorted(directory.rglob("*.bin"))
            if support.REFERENCE_ESSENTIAL_DIR not in path.parts and path.stat().st_size > TAG_IMAGE_LENGTH
        ]
        self.assertTrue(oversize, "the clone the index's intake rule was written against")
        for path in oversize:
            tag = slice_tag_image(path.read_bytes())
            unpack(tag, self.key)


if __name__ == "__main__":
    unittest.main()
